### ISSUE TITLE
go.mod should declare its package as github.com/openshift/... not sigs.k8s.io/...

### ISSUE THREAD

**Issue by 2uasimojo** [openshift/cluster-api-provider-ibmcloud#50]
go won't let me vendor this project unless I go back to 4.11, the last place where go.mod declared 

```
module github.com/openshift/cluster-api-provider-ibmcloud
```

It currently declares

```
module sigs.k8s.io/cluster-api-provider-ibmcloud
```

which results in

```
go: github.com/openshift/cluster-api-provider-ibmcloud@v0.0.0-20221221122817-e0a7ccca0237: parsing go.mod:
	module declares its path as: sigs.k8s.io/cluster-api-provider-ibmcloud
	        but was required as: github.com/openshift/cluster-api-provider-ibmcloud
```

when I try to vendor it.

Perhaps there's some way around this in my go.mod? I have tried as many permutations of `replace` as I have been able to discover the existence of, to no avail.

**Comment by Karthik-K-N** [comment]
Hi @2uasimojo , From 4.12 we have updated this repo to be in sync with upstream cluster-api project: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud.

and what you are seeing at 4.11 in this repo is moved to new repo from 4.12 named machine-api: https://github.com/openshift/machine-api-provider-ibmcloud

**Comment by 2uasimojo** [comment]
Ah, thanks! I just cut my import over to the latter and was able to make progress.

So IIUC as of 4.12 this project will not be vendorable at all due to this issue? Consumers wishing to use it would need to vendor the upstream repo?

**Comment by 2uasimojo** [comment]
...also, would it be worth updating the README in the fork to point this out?
